apiVersion: v1
description: GitLab's Auto-deploy Helm Chart for OpenShift (gitlab/auto-deploy-app 0.2.6)
name: auto-deploy-app
version: 0.0.5
icon: https://gitlab.com/gitlab-com/gitlab-artwork/raw/master/logo/logo-square.png
