# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: gitlab.example.com/group/project
  tag: stable
  pullPolicy: Always
  secrets:
    - name: gitlab-registry
application:
  track: stable
  tier: web
  migrateCommand:
  initializeCommand:
  serviceAccount:
  # secretName:
  server:
    tier: server
    serviceAccount:
service:
  enabled: true
  name: web
  type: ClusterIP
  url: http://my.host.com/
  externalPort: 5000
  internalPort: 5000
  server:
    enabled: false
    name: server
    url: http://server-my.host.com/
    externalPort: 4000
    internalPort: 4000
postgresql:
  enabled: false
mssql:
  enabled: false
redis:
  enabled: false
resources:
#  limits:
#    cpu: 100m
#    memory: 128Mi
#  requests:
#    cpu: 100m
#    memory: 128Mi
